### ISSUE TITLE
Please add transparency back

### ISSUE THREAD

**Issue by hazelnot** [hllvc/better-osd#1]
Just what the title says, please add transparency back as an option :(

**Comment by hllvc** [comment]
> Just what the title says, please add transparency back as an option :(

@hazelnot I hope by the end of week I would fond time to add it.. anyway I will add it back :)

**Comment by lonix1** [comment]
Yeah - looking forward to it too!

This extension is better than the original.

**Comment by lonix1** [comment]
Thanks!

I installed it but it didn't work, so I assume the new version isn't live yet.

How long does it usually take till they approve it?

**Comment by hllvc** [comment]
> Thanks!
> 
> I installed it but it didn't work, so I assume the new version isn't live yet.
> 
> How long does it usually take till they approve it?

I am currently using latest version, I had some bugs in but they were fixed. Version 4 is latest on GNOME Extensions.
Can you show me your error so I could help you?

**Comment by lonix1** [comment]
What I did:
- disabled the [original](https://extensions.gnome.org/extension/1345/better-osd/) "Better OSD" extension
- installed this extension
- <kbd>alt + f2</kbd> and <kbd>r + enter</kbd> to restart gnome shell
- opened extension's config

A popup appeared with this error:
> Something's gone wrong
We're very sorry, but there's been a problem; the settings for this extension can't be displayed. We recommend that you report the issue to the extension authors.

I clicked the "Technical Details" button:
> TypeError: hBox.prepend is not a function
Stack trace:
  _init@/home/username/.local/share/gnome-shell/extensions/better-osd@hllvc/prefs.js:55:12
  buildPrefsWidget@/home/username/.local/share/gnome-shell/extensions/better-osd@hllvc/prefs.js:201:10
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by hllvc** [comment]
> What I did:
> 
>     * disabled the [original](https://extensions.gnome.org/extension/1345/better-osd/) "Better OSD" extension
> 
>     * installed this extension
> 
>     * alt + f2 and r + enter to restart gnome shell
> 
>     * opened extension's config
> 
> 
> A popup appeared with this error:
> 
> > Something's gone wrong
> > We're very sorry, but there's been a problem; the settings for this extension can't be displayed. We recommend that you report the issue to the extension authors.
> 
> I clicked the "Technical Details" button:
> 
> > TypeError: hBox.prepend is not a function
> > Stack trace:
> > _init@/home/username/.local/share/gnome-shell/extensions/better-osd@hllvc/prefs.js:55:12
> > buildPrefsWidget@/home/username/.local/share/gnome-shell/extensions/better-osd@hllvc/prefs.js:201:10
> > _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
> > OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> > asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
> > run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
> > main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> > run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> > start@resource:///org/gnome/gjs/modules/script/package.js:206:5
> > @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

Thank you for your detailed explanation. Can you tell me which GNOME version are you on?

**Comment by lonix1** [comment]
Whichever comes with ubuntu 20

**Comment by hllvc** [comment]
> Whichever comes with Ubuntu 20.04?
> 
> 
> 
> ---
> 
> EDIT:
> 
> 
> 
> `gnome-shell --version` gives `3.36.9`
> 
> 
> 
> Ahhh... :laughing:
> 
> So this extension only supports bleeding edge. Most people are not on v40 yet.  

Unfortunately, yes. I used the original one when I was below 40. After updating it didn't work so I modified to work with 40.

**Comment by lonix1** [comment]
I guess I will continue to use old one.
One day when ubuntu upgrades to gnome 40 I'll start using this one!
Thanks for making it.
